export const symbolImageFileNames = {
    0: "0-ClearNight.png",
    1: "1-SunnyDay.png",
    2: "2-PartlyCloudyNight.png",
    3: "3-PartlyCloudyDay.png",
    5: "5-Mist.png",
    6: "6-Fog.png",
    7: "7-Cloudy.png",
    8: "8-Overcast.png",
    9: "9-LightRainShowerNight.png",
    10: "10-LightRainShowerDay.png",
    11: "11-Drizzle.png",
    12: "12-LightRain.png",
    13: "13-HeavyRainShowerNight.png",
    14: "14-HeavyRainShowerDay.png",
    15: "15-HeavyRain.png",
    16: "16-SleetShowerNight.png",
    17: "17-SleetShowerDay.png",
    18: "18-Sleet.png",
    19: "19-HailShowerNight.png",
    20: "20-HailShowerDay.png",
    21: "21-Hail.png",
    22: "22-LightSnowShowerNight.png",
    23: "23-LightSnowShowerDay.png",
    24: "24-LightSnow.png",
    25: "25-HeavySnowShowerNight.png",
    26: "26-HeavySnowShowerDay.png",
    27: "27-HeavySnow.png",
    28: "28-ThunderShowerNight.png",
    29: "29-ThunderShowerDay.png",
    30: "30-Thunder.png"
};

export enum WeatherCode {
    TraceRain = -1,
    ClearNight = 0,
    SunnyDay = 1,
    PartlyCloudyNight = 2,
    PartlyCloudyDay = 3,
    Mist = 5,
    Fog = 6,
    Cloudy = 7,
    Overcast = 8,
    LightRainShowerNight = 9,
    LightRainShowerDay = 10,
    Drizzle = 11,
    LightRain = 12,
    HeavyRainShowerNight = 13,
    HeavyRainShowerDay = 14,
    HeavyRain = 15,
    SleetShowerNight = 16,
    SleetShowerDay = 17,
    Sleet = 18,
    HailShowerNight = 19,
    HailShowerDay = 20,
    Hail = 21,
    LightSnowShowerNight = 22,
    LightSnowShowerDay = 23,
    LightSnow = 24,
    HeavySnowShowerNight = 25,
    HeavySnowShowerDay = 26,
    HeavySnow = 27,
    ThunderShowerNight = 28,
    ThunderShowerDay = 29,
    Thunder = 30
}